name: Percy Visual Tests

on:
  pull_request:
    branches:
      - master

jobs:
  percy-visual-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Run the development server (for Component Testing)
      - name: Start development server
        run: yarn start &
        env:
          PORT: 3000

      # Step 5: Run Percy with Cypress Component Testing
      - name: Run Percy and Cypress
        run: npx percy exec -- cypress run --component
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
