name: Percy CI

on:
  pull_request:
    branches:
      - master # Run workflow on pull requests targeting the master branch

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "18" # Update Node.js to version 16 or later

      # Step 3: Install dependencies
      - run: yarn install

      # Step 4: Install Percy CLI
      - run: yarn add --save-dev @percy/cli

      # Step 5: Run Percy snapshots
      - run: npx percy snapshot ./ # Update with your snapshot directory
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }} # Use the secret for secure token access
